const Map<String, Map<String, dynamic>> languages = {
  "English": {
    "title": "Cotton Disease Detection",
    "upload_image": "Upload Image",
    "click_image": "Capture Image",
    "switch_language": "Switch to Hindi",
    "detect_disease": "Detect Disease in Cotton",
    "processing": "Processing image...",
    "no_image": "No image selected.",
    "model_error": "Error loading model.",
    "disease_detected": "Detected Disease: ",
    "remedy": "Remedy: ",
    "healthy": "No issues detected.",
    "diseases": ["Bacterial Blight", "Curl Virus", "Fusarium Wilt", "Healthy"],
    "remedies": [
      "Apply copper-based sprays.",
      "Control pests with neem oil.",
      "Use fungicides and avoid overwatering.",
      "No issues detected."
    ],
  },
  "Hindi": {
    "title": "कपास रोग पहचान",
    "upload_image": "छवि अपलोड करें",
    "click_image": "छवि कैप्चर करें",
    "switch_language": "मराठी में बदलें",
    "detect_disease": "कपास में रोग का पता लगाएं",
    "processing": "छवि प्रोसेसिंग...",
    "no_image": "कोई छवि चयनित नहीं हुई।",
    "model_error": "मॉडल लोड करने में त्रुटि।",
    "disease_detected": "पहचाना गया रोग: ",
    "remedy": "उपचार: ",
    "healthy": "कोई समस्या नहीं मिली।",
    "diseases": ["कर्ल वायरस", "बैक्टीरियल ब्लाइट", "फ्यूजेरियम विल्ट", "स्वस्थ"],
    "remedies": [
      "फफूंदनाशकों का प्रयोग करें और अत्यधिक सिंचाई से बचें।",
      "कॉपर-आधारित स्प्रे का उपयोग करें।",
      "नीम के तेल से कीटों को नियंत्रित करें।",
      "कोई समस्या नहीं मिली।"
    ],
  },
  "Telugu": {
    "title": "పత్తి వ్యాధి గుర్తింపు",
    "upload_image": "చిత్రాన్ని అప్‌లోడ్ చేయండి",
    "click_image": "చిత్రాన్ని క్లిక్ చేయండి",
    "switch_language": "मराठीకి మారండి",
    "detect_disease": "పత్తిలో వ్యాధిని గుర్తించండి",
    "processing": "చిత్రాన్ని ప్రాసెస్ చేస్తోంది...",
    "no_image": "చిత్రం ఎంచుకోలేదు.",
    "model_error": "మోడల్ లోడ్ చేయడంలో లోపం.",
    "disease_detected": "గుర్తించిన వ్యాధి: ",
    "remedy": "పరిష్కారం: ",
    "healthy": "ఎటువంటి సమస్య లేదు.",
    "diseases": ["కర్ల్ వైరస్", "బ్యాక్టీరియల్ బ్లైట్", "ఫ్యూసేరియం విల్ట్", "ఆరోగ్యంగా ఉంది"],
    "remedies": [
      "ఫంగిసైడ్లను ఉపయోగించండి మరియు అధిక నీటిపారుదల నివారించండి.",
      "కాపర్ ఆధారిత స్ప్రేలను ఉపయోగించండి.",
      "నీమ్స్ నూనెతో పురుగులను నియంత్రించండి.",
      "ఎటువంటి సమస్య లేదు."
    ],
  },
  "Marathi": {
    "title": "कापूस रोग ओळख",
    "upload_image": "प्रतिमा अपलोड करा",
    "click_image": "प्रतिमा कॅप्चर करा",
    "switch_language": "इंग्रजीसाठी बदला",
    "detect_disease": "कापसामध्ये रोग शोधा",
    "processing": "प्रतिमा प्रक्रिया होत आहे...",
    "no_image": "कोणतीही प्रतिमा निवडलेली नाही.",
    "model_error": "मॉडेल लोड करण्यात त्रुटी.",
    "disease_detected": "शोधलेला रोग: ",
    "remedy": "उपाय: ",
    "healthy": "कोणतीही समस्या आढळली नाही.",
    "diseases": ["कर्ल व्हायरस", "बॅक्टेरियल ब्लाइट", "फ्युसेरियम विल्ट", "निरोगी"],
    "remedies": [
      "बुरशीनाशके वापरा आणि जास्त पाणी टाळा.",
      "तांब्याच्या-आधारित फवारण्या लागू करा.",
      "नीम तेलाने कीटक नियंत्रित करा.",
      "कोणतीही समस्या आढळली नाही."
    ],
  },
};
